/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesRentAChefRouteImport } from './routes/case-studies.rent-a-chef'
import { Route as CaseStudiesFamilyOfficeBillingRouteImport } from './routes/case-studies.family-office-billing'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRentAChefRoute = CaseStudiesRentAChefRouteImport.update({
  id: '/case-studies/rent-a-chef',
  path: '/case-studies/rent-a-chef',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesFamilyOfficeBillingRoute =
  CaseStudiesFamilyOfficeBillingRouteImport.update({
    id: '/case-studies/family-office-billing',
    path: '/case-studies/family-office-billing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/case-studies/family-office-billing': typeof CaseStudiesFamilyOfficeBillingRoute
  '/case-studies/rent-a-chef': typeof CaseStudiesRentAChefRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/case-studies/family-office-billing': typeof CaseStudiesFamilyOfficeBillingRoute
  '/case-studies/rent-a-chef': typeof CaseStudiesRentAChefRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/case-studies/family-office-billing': typeof CaseStudiesFamilyOfficeBillingRoute
  '/case-studies/rent-a-chef': typeof CaseStudiesRentAChefRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancellation-policy'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/case-studies/family-office-billing'
    | '/case-studies/rent-a-chef'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancellation-policy'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/case-studies/family-office-billing'
    | '/case-studies/rent-a-chef'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/cancellation-policy'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/case-studies/family-office-billing'
    | '/case-studies/rent-a-chef'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  CaseStudiesFamilyOfficeBillingRoute: typeof CaseStudiesFamilyOfficeBillingRoute
  CaseStudiesRentAChefRoute: typeof CaseStudiesRentAChefRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/rent-a-chef': {
      id: '/case-studies/rent-a-chef'
      path: '/case-studies/rent-a-chef'
      fullPath: '/case-studies/rent-a-chef'
      preLoaderRoute: typeof CaseStudiesRentAChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/family-office-billing': {
      id: '/case-studies/family-office-billing'
      path: '/case-studies/family-office-billing'
      fullPath: '/case-studies/family-office-billing'
      preLoaderRoute: typeof CaseStudiesFamilyOfficeBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  CaseStudiesFamilyOfficeBillingRoute: CaseStudiesFamilyOfficeBillingRoute,
  CaseStudiesRentAChefRoute: CaseStudiesRentAChefRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
